//===================================================
//作    者：DRB
//创建时间：2021-04-05 20:52:24
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// S2C_Result
/// </summary>
public class Mahjong_S2C_ResultProto : IProto
{
    public int Code { get { return 30009; } }

    public Seat seat; //
    public int pos; //
    public int playerId; //
    public int gold; //
    public bool isWinner; //

    /// <summary>
    /// 
    /// </summary>
    public class Seat
    {
        public Seat()
        {
        }

        public Seat(byte[] bytes)
        {
            Deserialize(bytes);
        }

        public byte[] Serialize()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                return ms.ToArray();
            }
        }

        public void Deserialize(byte[] buffer)
        {
            if (buffer == null) return;
            using (MemoryStream ms = new MemoryStream(buffer))
            {
            }
        }
    }

    public Mahjong_S2C_ResultProto()
    {
    }

    public Mahjong_S2C_ResultProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            if(seat != null)
            {
                ms.WriteBytes(seat.Serialize());
            }
            else
            {
                ms.WriteInt(0);
            }
            ms.WriteInt(pos);
            ms.WriteInt(playerId);
            ms.WriteInt(gold);
            ms.WriteBool(isWinner);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            seat = new Seat(ms.ReadBytes());
            pos = ms.ReadInt();
            playerId = ms.ReadInt();
            gold = ms.ReadInt();
            isWinner = ms.ReadBool();
        }
    }
}
