//===================================================
//作    者：DRB
//创建时间：2021-04-05 20:52:24
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// S2C_Turn
/// </summary>
public class Mahjong_S2C_TurnProto : IProto
{
    public int Code { get { return 30005; } }

    public long countdown; //
    public List<PokerGroup> askPokerGroupList; //

    /// <summary>
    /// 
    /// </summary>
    public class PokerGroup
    {
        public byte typeId; //
        public byte subTypeId; //
        public int playerId; //
        public Poker pokers; //
        public PokerGroup()
        {
        }

        public PokerGroup(byte[] bytes)
        {
            Deserialize(bytes);
        }

        public byte[] Serialize()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                ms.WriteByte(typeId);
                ms.WriteByte(subTypeId);
                ms.WriteInt(playerId);
                if(pokers != null)
                {
                    ms.WriteBytes(pokers.Serialize());
                }
                else
                {
                    ms.WriteInt(0);
                }
                return ms.ToArray();
            }
        }

        public void Deserialize(byte[] buffer)
        {
            if (buffer == null) return;
            using (MemoryStream ms = new MemoryStream(buffer))
            {
                typeId = (byte)ms.ReadByte();
                subTypeId = (byte)ms.ReadByte();
                playerId = ms.ReadInt();
                pokers = new Poker(ms.ReadBytes());
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    public class Poker
    {
        public int index; //
        public int color; //
        public int number; //
        public int pos; //
        public Poker()
        {
        }

        public Poker(byte[] bytes)
        {
            Deserialize(bytes);
        }

        public byte[] Serialize()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                ms.WriteInt(index);
                ms.WriteInt(color);
                ms.WriteInt(number);
                ms.WriteInt(pos);
                return ms.ToArray();
            }
        }

        public void Deserialize(byte[] buffer)
        {
            if (buffer == null) return;
            using (MemoryStream ms = new MemoryStream(buffer))
            {
                index = ms.ReadInt();
                color = ms.ReadInt();
                number = ms.ReadInt();
                pos = ms.ReadInt();
            }
        }
    }

    public Mahjong_S2C_TurnProto()
    {
    }

    public Mahjong_S2C_TurnProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteLong(countdown);
            ms.WriteUShort((ushort)(askPokerGroupList == null?0:askPokerGroupList.Count));
            if(askPokerGroupList != null)
            {
                for (int i = 0; i < askPokerGroupList.Count; ++i)
                {
                    if(askPokerGroupList[i] != null)
                    {
                        ms.WriteBytes(askPokerGroupList[i].Serialize());
                    }
                    else
                    {
                        ms.WriteInt(0);
                    }
                }
            }
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            countdown = ms.ReadLong();
            ushort askPokerGroupListLength = ms.ReadUShort();
            askPokerGroupList = new List<PokerGroup>();
            for (int i = 0; i < askPokerGroupListLength; ++i)
            {
                askPokerGroupList.Add(new PokerGroup(ms.ReadBytes()));
            }
        }
    }
}
