//===================================================
//作    者：DRB
//创建时间：2021-04-23 08:04:28
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// C2S_Discard
/// </summary>
public class Mahjong_C2S_DiscardProto : IProto
{
    public int Code { get { return 30003; } }

    public int index; //
    public bool isReadyHand; //

    public Mahjong_C2S_DiscardProto()
    {
    }

    public Mahjong_C2S_DiscardProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteInt(index);
            ms.WriteBool(isReadyHand);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            index = ms.ReadInt();
            isReadyHand = ms.ReadBool();
        }
    }
}
