//===================================================
//作    者：DRB
//创建时间：2021-04-05 20:52:24
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// C2S_Operate
/// </summary>
public class Mahjong_C2S_OperateProto : IProto
{
    public int Code { get { return 30006; } }

    public byte typeId; //
    public int index; //

    public Mahjong_C2S_OperateProto()
    {
    }

    public Mahjong_C2S_OperateProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteByte(typeId);
            ms.WriteInt(index);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            typeId = (byte)ms.ReadByte();
            index = ms.ReadInt();
        }
    }
}
