
//===================================================
//Author：DRB
//CreateTime：2021/4/27 21:17:20
//Remark：This code is generated by the tool
//===================================================
package com.oegame.tablegames.model.local.gen;
import com.oegame.tablegames.common.util.StringUtil;
import com.oegame.tablegames.model.local.*;

// Games数据管理
public class GamesDBModel extends AbstractDBModel<GamesEntity>
{
    private static GamesDBModel dbModel = new GamesDBModel();
    public static GamesDBModel singleton()
    {
        return dbModel;
    }
    private GamesDBModel() { }
    // 文件名称
    protected String getFileName() {return "Games.drb";}

    /// 创建实体
    protected GamesEntity makeEntity(LocalDataParser parse)
    {
        GamesEntity entity = new GamesEntity();
        entity.id = StringUtil.toInt(parse.getFieldValue("id"));
        entity.gameName = (parse.getFieldValue("gameName"));
        entity.gameType = (parse.getFieldValue("gameType"));
        entity.gameLabel = (parse.getFieldValue("gameLabel"));
        entity.sceneName = (parse.getFieldValue("sceneName"));
        entity.bGM = (parse.getFieldValue("bGM"));
        entity.icon = (parse.getFieldValue("icon"));
        entity.sceneUI = (parse.getFieldValue("sceneUI"));
        entity.configPath = (parse.getFieldValue("configPath"));
        return entity;
    }
}
