
//===================================================
//Author：DRB
//CreateTime：2021/4/27 21:17:20
//Remark：This code is generated by the tool
//===================================================
package com.oegame.tablegames.model.local.gen;
import com.oegame.tablegames.model.local.*;

// Games实体
public class GamesEntity extends AbstractEntity
{
    // Game Name
    public String gameName;

    // Game Type
    public String gameType;

    // Game Lable
    public String gameLabel;

    // Scene Name
    public String sceneName;

    // BGM
    public String bGM;

    // Icon
    public String icon;

    // Scene UI
    public String sceneUI;

    // Config Path
    public String configPath;

}
