
//===================================================
//Author：DRB
//CreateTime：2021/4/6 1:13:59
//Remark：This code is generated by the tool
//===================================================
package com.oegame.tablegames.model.local.gen;
import com.oegame.tablegames.model.local.*;

// MahjongSettings实体
public class MahjongSettingsEntity extends AbstractEntity
{
    // Descrption
    public String descrption;

    // Game Name
    public String gameName;

    // Game ID
    public int gameId;

    // Lable
    public String label;

    // Name
    public String name;

    // Tags
    public String tags;

    // Select Mode
    public int mode;

    // Value
    public int value;

    // Cost
    public int cost;

    // Status
    public int status;

    // Default Selected
    public boolean selected;

}
