//===================================================
//Author      : DRB
//CreateTime  ：2021/3/7 0:10:04
//Description ：
//===================================================
//===================================================
//作    者：DRB
//创建时间：2021-03-07 00:08:53
//备    注：this code is generated by the tool
//===================================================
using System.Collections.Generic;

/// <summary>
/// 协议编号定义
/// </summary>
public static class CodeDef
{
    /// <summary>
    /// HeartBeat
    /// </summary>
    public const int System_HeartBeatProto = 10001;

    /// <summary>
    /// Disconnect
    /// </summary>
    public const int System_DisconnectProto = 10002;

    private readonly static Dictionary<int, string> DicCn = new Dictionary<int, string>();
    private readonly static Dictionary<int, string> DicEn = new Dictionary<int, string>();

    static CodeDef()
    {
        DicCn[System_HeartBeatProto] = "HeartBeat";
        DicEn[System_HeartBeatProto] = "System_HeartBeatProto";
        DicCn[System_DisconnectProto] = "Disconnect";
        DicEn[System_DisconnectProto] = "System_DisconnectProto";
    }
    public static string GetCn(int code)
    {
        if(!DicCn.ContainsKey(code)) return "未知消息";
        return DicCn[code];
    }
    public static string GetEn(int code)
    {
        if(!DicEn.ContainsKey(code)) return "Unknown protocol";
        return DicEn[code];
    }
}
