//===================================================
//作    者：DRB
//创建时间：2021-04-15 02:37:17
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// C2S_EnterRoom
/// </summary>
public class Game_C2S_EnterRoomProto : IProto
{
    public int Code { get { return 20002; } }

    public int roomId; //room id
    public int gameId; //game id

    public Game_C2S_EnterRoomProto()
    {
    }

    public Game_C2S_EnterRoomProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteInt(roomId);
            ms.WriteInt(gameId);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            roomId = ms.ReadInt();
            gameId = ms.ReadInt();
        }
    }
}
