//===================================================
//作    者：DRB
//创建时间：2021-04-15 03:55:33
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// C2S_QueryRoomInfo
/// </summary>
public class Game_C2S_QueryRoomInfoProto : IProto
{
    public int Code { get { return 20012; } }

    public int roomId; //

    public Game_C2S_QueryRoomInfoProto()
    {
    }

    public Game_C2S_QueryRoomInfoProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteInt(roomId);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            roomId = ms.ReadInt();
        }
    }
}
