//===================================================
//作    者：DRB
//创建时间：2021-04-15 02:37:17
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// C2S_Ready
/// </summary>
public class Game_C2S_ReadyProto : IProto
{
    public int Code { get { return 20006; } }


    public Game_C2S_ReadyProto()
    {
    }

    public Game_C2S_ReadyProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
        }
    }
}
