//===================================================
//作    者：DRB
//创建时间：2021-04-23 03:30:18
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// S2C_OperationWait
/// </summary>
public class Mahjong_S2C_OperationWaitProto : IProto
{
    public int Code { get { return 30014; } }


    public Mahjong_S2C_OperationWaitProto()
    {
    }

    public Mahjong_S2C_OperationWaitProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
        }
    }
}
