//===================================================
//作    者：DRB
//创建时间：2021-04-15 02:37:17
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// C2S_Operate
/// </summary>
public class Mahjong_C2S_OperateProto : IProto
{
    public int Code { get { return 30006; } }

    public byte typeId; //
    public List<int> indexList; //

    public Mahjong_C2S_OperateProto()
    {
    }

    public Mahjong_C2S_OperateProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteByte(typeId);
            ms.WriteUShort((ushort)(indexList == null?0:indexList.Count));
            if(indexList != null)
            {
                for (int i = 0; i < indexList.Count; ++i)
                {
                    ms.WriteInt(indexList[i]);
                }
            }
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            typeId = (byte)ms.ReadByte();
            ushort indexListLength = ms.ReadUShort();
            indexList = new List<int>();
            for (int i = 0; i < indexListLength; ++i)
            {
                indexList.Add(ms.ReadInt());
            }
        }
    }
}
