//===================================================
//作    者：DRB
//创建时间：2021-04-23 03:30:18
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// S2C_Draw
/// </summary>
public class Mahjong_S2C_DrawProto : IProto
{
    public int Code { get { return 30002; } }

    public int playerId; //
    public long countdown; //
    public int index; //
    public int color; //
    public int number; //
    public bool isFromLast; //

    public Mahjong_S2C_DrawProto()
    {
    }

    public Mahjong_S2C_DrawProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteInt(playerId);
            ms.WriteLong(countdown);
            ms.WriteInt(index);
            ms.WriteInt(color);
            ms.WriteInt(number);
            ms.WriteBool(isFromLast);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            playerId = ms.ReadInt();
            countdown = ms.ReadLong();
            index = ms.ReadInt();
            color = ms.ReadInt();
            number = ms.ReadInt();
            isFromLast = ms.ReadBool();
        }
    }
}
