//===================================================
//作    者：DRB
//创建时间：2021-04-28 02:06:09
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// S2C_Settle
/// </summary>
public class Mahjong_S2C_SettleProto : IProto
{
    public int Code { get { return 30008; } }

    public bool isOver; //
    public List<Seat> seatsList; //

    /// <summary>
    /// 
    /// </summary>
    public class Seat
    {
        public byte status; //
        public bool isLoser; //
        public bool isWinner; //
        public bool isReadyHand; //
        public int playerId; //
        public int pos; //
        public int gold; //
        public int settle; //
        public Mahjong universalPoker; //
        public Mahjong hitMahjong; //
        public List<Mahjong> mahjongsList; //
        public List<Mahjong> desktopMahjongsList; //
        public string incomesDesc = ""; //
        public List<MahjongGroup> usedMahjongGroupList; //
        public Seat()
        {
        }

        public Seat(byte[] bytes)
        {
            Deserialize(bytes);
        }

        public byte[] Serialize()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                ms.WriteByte(status);
                ms.WriteBool(isLoser);
                ms.WriteBool(isWinner);
                ms.WriteBool(isReadyHand);
                ms.WriteInt(playerId);
                ms.WriteInt(pos);
                ms.WriteInt(gold);
                ms.WriteInt(settle);
                if(universalPoker != null)
                {
                    ms.WriteBytes(universalPoker.Serialize());
                }
                else
                {
                    ms.WriteInt(0);
                }
                if(hitMahjong != null)
                {
                    ms.WriteBytes(hitMahjong.Serialize());
                }
                else
                {
                    ms.WriteInt(0);
                }
                ms.WriteUShort((ushort)(mahjongsList == null?0:mahjongsList.Count));
                if(mahjongsList != null)
                {
                    for (int i = 0; i < mahjongsList.Count; ++i)
                    {
                        if(mahjongsList[i] != null)
                        {
                            ms.WriteBytes(mahjongsList[i].Serialize());
                        }
                        else
                        {
                            ms.WriteInt(0);
                        }
                    }
                }
                ms.WriteUShort((ushort)(desktopMahjongsList == null?0:desktopMahjongsList.Count));
                if(desktopMahjongsList != null)
                {
                    for (int i = 0; i < desktopMahjongsList.Count; ++i)
                    {
                        if(desktopMahjongsList[i] != null)
                        {
                            ms.WriteBytes(desktopMahjongsList[i].Serialize());
                        }
                        else
                        {
                            ms.WriteInt(0);
                        }
                    }
                }
                ms.WriteUTF8String(incomesDesc);
                ms.WriteUShort((ushort)(usedMahjongGroupList == null?0:usedMahjongGroupList.Count));
                if(usedMahjongGroupList != null)
                {
                    for (int i = 0; i < usedMahjongGroupList.Count; ++i)
                    {
                        if(usedMahjongGroupList[i] != null)
                        {
                            ms.WriteBytes(usedMahjongGroupList[i].Serialize());
                        }
                        else
                        {
                            ms.WriteInt(0);
                        }
                    }
                }
                return ms.ToArray();
            }
        }

        public void Deserialize(byte[] buffer)
        {
            if (buffer == null) return;
            using (MemoryStream ms = new MemoryStream(buffer))
            {
                status = (byte)ms.ReadByte();
                isLoser = ms.ReadBool();
                isWinner = ms.ReadBool();
                isReadyHand = ms.ReadBool();
                playerId = ms.ReadInt();
                pos = ms.ReadInt();
                gold = ms.ReadInt();
                settle = ms.ReadInt();
                byte[] universalPokerBytes = ms.ReadBytes();
                if(universalPokerBytes != null) universalPoker = new Mahjong(universalPokerBytes);
                byte[] hitMahjongBytes = ms.ReadBytes();
                if(hitMahjongBytes != null) hitMahjong = new Mahjong(hitMahjongBytes);
                ushort mahjongsListLength = ms.ReadUShort();
                mahjongsList = new List<Mahjong>();
                for (int i = 0; i < mahjongsListLength; ++i)
                {
                    byte[] mahjongsBytes = ms.ReadBytes();
                    if(mahjongsBytes != null) mahjongsList.Add(new Mahjong(mahjongsBytes));
                }
                ushort desktopMahjongsListLength = ms.ReadUShort();
                desktopMahjongsList = new List<Mahjong>();
                for (int i = 0; i < desktopMahjongsListLength; ++i)
                {
                    byte[] desktopMahjongsBytes = ms.ReadBytes();
                    if(desktopMahjongsBytes != null) desktopMahjongsList.Add(new Mahjong(desktopMahjongsBytes));
                }
                incomesDesc = ms.ReadUTF8String();
                ushort usedMahjongGroupListLength = ms.ReadUShort();
                usedMahjongGroupList = new List<MahjongGroup>();
                for (int i = 0; i < usedMahjongGroupListLength; ++i)
                {
                    byte[] usedMahjongGroupBytes = ms.ReadBytes();
                    if(usedMahjongGroupBytes != null) usedMahjongGroupList.Add(new MahjongGroup(usedMahjongGroupBytes));
                }
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    public class Mahjong
    {
        public int index; //
        public int color; //
        public int number; //
        public int pos; //
        public Mahjong()
        {
        }

        public Mahjong(byte[] bytes)
        {
            Deserialize(bytes);
        }

        public byte[] Serialize()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                ms.WriteInt(index);
                ms.WriteInt(color);
                ms.WriteInt(number);
                ms.WriteInt(pos);
                return ms.ToArray();
            }
        }

        public void Deserialize(byte[] buffer)
        {
            if (buffer == null) return;
            using (MemoryStream ms = new MemoryStream(buffer))
            {
                index = ms.ReadInt();
                color = ms.ReadInt();
                number = ms.ReadInt();
                pos = ms.ReadInt();
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    public class MahjongGroup
    {
        public byte typeId; //
        public byte subTypeId; //
        public List<Mahjong> mahjongsList; //
        public MahjongGroup()
        {
        }

        public MahjongGroup(byte[] bytes)
        {
            Deserialize(bytes);
        }

        public byte[] Serialize()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                ms.WriteByte(typeId);
                ms.WriteByte(subTypeId);
                ms.WriteUShort((ushort)(mahjongsList == null?0:mahjongsList.Count));
                if(mahjongsList != null)
                {
                    for (int i = 0; i < mahjongsList.Count; ++i)
                    {
                        if(mahjongsList[i] != null)
                        {
                            ms.WriteBytes(mahjongsList[i].Serialize());
                        }
                        else
                        {
                            ms.WriteInt(0);
                        }
                    }
                }
                return ms.ToArray();
            }
        }

        public void Deserialize(byte[] buffer)
        {
            if (buffer == null) return;
            using (MemoryStream ms = new MemoryStream(buffer))
            {
                typeId = (byte)ms.ReadByte();
                subTypeId = (byte)ms.ReadByte();
                ushort mahjongsListLength = ms.ReadUShort();
                mahjongsList = new List<Mahjong>();
                for (int i = 0; i < mahjongsListLength; ++i)
                {
                    byte[] mahjongsBytes = ms.ReadBytes();
                    if(mahjongsBytes != null) mahjongsList.Add(new Mahjong(mahjongsBytes));
                }
            }
        }
    }

    public Mahjong_S2C_SettleProto()
    {
    }

    public Mahjong_S2C_SettleProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteBool(isOver);
            ms.WriteUShort((ushort)(seatsList == null?0:seatsList.Count));
            if(seatsList != null)
            {
                for (int i = 0; i < seatsList.Count; ++i)
                {
                    if(seatsList[i] != null)
                    {
                        ms.WriteBytes(seatsList[i].Serialize());
                    }
                    else
                    {
                        ms.WriteInt(0);
                    }
                }
            }
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            isOver = ms.ReadBool();
            ushort seatsListLength = ms.ReadUShort();
            seatsList = new List<Seat>();
            for (int i = 0; i < seatsListLength; ++i)
            {
                byte[] seatsBytes = ms.ReadBytes();
                if(seatsBytes != null) seatsList.Add(new Seat(seatsBytes));
            }
        }
    }
}
