//===================================================
//作    者：DRB
//创建时间：2021-04-28 02:06:09
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// S2C_Discard
/// </summary>
public class Mahjong_S2C_DiscardProto : IProto
{
    public int Code { get { return 30004; } }

    public int playerId; //
    public int index; //
    public int color; //
    public int number; //
    public bool isReadyHand; //

    public Mahjong_S2C_DiscardProto()
    {
    }

    public Mahjong_S2C_DiscardProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteInt(playerId);
            ms.WriteInt(index);
            ms.WriteInt(color);
            ms.WriteInt(number);
            ms.WriteBool(isReadyHand);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            playerId = ms.ReadInt();
            index = ms.ReadInt();
            color = ms.ReadInt();
            number = ms.ReadInt();
            isReadyHand = ms.ReadBool();
        }
    }
}
