//===================================================
//作    者：DRB
//创建时间：2021-04-23 03:30:18
//备    注：this code is generated by the tool
//===================================================
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using DrbFramework.Internal.Network;
using DrbFramework.Extensions;

/// <summary>
/// C2S_HeartBeat
/// </summary>
public class System_C2S_HeartBeatProto : IProto
{
    public int Code { get { return 10001; } }

    public long clientTimestamp; //

    public System_C2S_HeartBeatProto()
    {
    }

    public System_C2S_HeartBeatProto(byte[] bytes)
    {
        Deserialize(bytes);
    }

    public byte[] Serialize()
    {
        using (MemoryStream ms = new MemoryStream())
        {
            ms.WriteInt(Code);
            ms.WriteLong(clientTimestamp);
            return ms.ToArray();
        }
    }

    public void Deserialize(byte[] buffer)
    {
        if (buffer == null) return;
        using (MemoryStream ms = new MemoryStream(buffer))
        {
            clientTimestamp = ms.ReadLong();
        }
    }
}
