
//===================================================
//Author：DRB
//CreateTime：2021/4/27 21:37:00
//Remark：This code is generated by the tool
//===================================================

using DrbFramework.DataTable;
using DrbFramework.Extensions;
using System.Collections;

/// <summary>
/// Games实体
/// </summary>
public partial class GamesDataEntity : IDataEntity
{
    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }

    /// <summary>
    /// Game Name
    /// </summary>
    public string GameName { get; private set; }

    /// <summary>
    /// Game Type
    /// </summary>
    public string GameType { get; private set; }

    /// <summary>
    /// Game Lable
    /// </summary>
    public string GameLabel { get; private set; }

    /// <summary>
    /// Scene Name
    /// </summary>
    public string SceneName { get; private set; }

    /// <summary>
    /// BGM
    /// </summary>
    public string BGM { get; private set; }

    /// <summary>
    /// Icon
    /// </summary>
    public string Icon { get; private set; }

    /// <summary>
    /// Scene UI
    /// </summary>
    public string SceneUI { get; private set; }

    /// <summary>
    /// Config Path
    /// </summary>
    public string ConfigPath { get; private set; }

    /// <summary>
    /// Procedure Name
    /// </summary>
    public string ProcedureName { get; private set; }

    /// <summary>
    /// 行数据
    /// </summary>
    public IDataRow DataRow { get; private set; }

    public void MakeEntity(IDataRow row)
    {
        Id = row.GetFieldValue("Id").ToInt();
        GameName = row.GetFieldValue("GameName");
        GameType = row.GetFieldValue("GameType");
        GameLabel = row.GetFieldValue("GameLabel");
        SceneName = row.GetFieldValue("SceneName");
        BGM = row.GetFieldValue("BGM");
        Icon = row.GetFieldValue("Icon");
        SceneUI = row.GetFieldValue("SceneUI");
        ConfigPath = row.GetFieldValue("ConfigPath");
        ProcedureName = row.GetFieldValue("ProcedureName");
        DataRow = row;
    }
}
